name: ecommerceapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  flutter_svg: ^1.0.3
  image_picker: ^0.8.5
  syncfusion_flutter_datepicker: ^20.1.48
  firebase_storage: ^10.2.11
  font_awesome_flutter: ^10.1.0
  get: ^4.6.1
  firebase_auth: ^3.3.14
  get_it: ^7.2.0
  google_sign_in: ^5.3.0
  file_picker: ^4.5.1
  intl: ^0.17.0
  rxdart: ^0.27.3
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  curved_navigation_bar: ^1.0.3


  flutter_vector_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/